image:
  repository:
  tag: latest

user-service:
  replicaCount: 1
  image:
    repository: local/user-service
    tag: 0.1.0
  env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://host.docker.internal:5432/userdb
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: postgres
    - name: JWT_SECRET
      value: super-secret-change-me

post-service:
  replicaCount: 1

search-service:
  replicaCount: 1